version: '2'

services:
  postgresql-master:
    image: bitnami/postgresql:12.4.0
    ports:
      - ${POSTGRESQL_MASTER_PORT}:5432
    volumes:
      - postgresql_master_data:/bitnami/postgresql
    environment:
        POSTGRESQL_REPLICATION_MODE: master
        POSTGRESQL_REPLICATION_USER: ${POSTGRESQL_REPLICATION_USER}
        POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
        POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
        POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
        POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}

  postgresql-slave:
    image: bitnami/postgresql:12.4.0
    ports:
      - ${POSTGRESQL_SLAVE_PORT}:5432
    depends_on:
      - postgresql-master
    environment:
        POSTGRESQL_REPLICATION_MODE: slave
        POSTGRESQL_MASTER_HOST: ${POSTGRESQL_MASTER_HOST}
        POSTGRESQL_MASTER_PORT_NUMBER: ${POSTGRESQL_MASTER_PORT}
        POSTGRESQL_REPLICATION_USER: ${POSTGRESQL_REPLICATION_USER}
        POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
        POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
        POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgresql_master_data:
