apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nest-typeorm
  name: nest-typeorm-config-map
data:
  POSTGRESQL_HOST: nest-typeorm-db-postgresql-ha-pgpool
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_DATABASE: nest-typeorm
